import React, { useState, useEffect } from 'react';
import { View, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import { Card, Title, Paragraph, useTheme, Chip, Button, TextInput, DataTable } from 'react-native-paper';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useSelector } from 'react-redux';
import { RootState } from '../../store';
import { useUI } from '../../contexts/ThemeContext';
import { adminAPI } from '../../utils/api';

interface ReportData {
  id: string;
  title: string;
  type: string;
  period: string;
  status: string;
  createdAt: string;
  generatedBy: string;
  downloadCount: number;
}

const AdminReporting: React.FC = () => {
  const theme = useTheme();
  const { user } = useSelector((state: RootState) => state.auth);
  const { showLoader, showToast } = useUI();

  const [reports, setReports] = useState<ReportData[]>([]);
  const [loading, setLoading] = useState(false);
  const [filter, setFilter] = useState({
    type: 'all',
    period: 'all',
    status: 'all',
  });

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      setLoading(true);
      showLoader(true);
      
      // Mock data for now - replace with actual API call
      const mockReports: ReportData[] = [
        {
          id: '1',
          title: 'Monthly Payroll Summary',
          type: 'payroll',
          period: 'January 2025',
          status: 'completed',
          createdAt: '2025-01-15',
          generatedBy: 'Admin User',
          downloadCount: 12,
        },
        {
          id: '2',
          title: 'Attendance Analytics',
          type: 'attendance',
          period: 'January 2025',
          status: 'completed',
          createdAt: '2025-01-14',
          generatedBy: 'Admin User',
          downloadCount: 8,
        },
        {
          id: '3',
          title: 'Employee Performance Report',
          type: 'performance',
          period: 'Q4 2024',
          status: 'pending',
          createdAt: '2025-01-13',
          generatedBy: 'Admin User',
          downloadCount: 0,
        },
        {
          id: '4',
          title: 'Financial Summary',
          type: 'financial',
          period: 'December 2024',
          status: 'completed',
          createdAt: '2024-12-31',
          generatedBy: 'Admin User',
          downloadCount: 15,
        },
      ];
      
      setReports(mockReports);
    } catch (error) {
      console.log('Error loading reports:', error);
      showToast('Failed to load reports', 'error');
    } finally {
      setLoading(false);
      showLoader(false);
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return '#4CAF50';
      case 'pending': return '#FF9800';
      case 'failed': return '#F44336';
      default: return theme.colors.onSurface;
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'payroll': return 'cash-multiple';
      case 'attendance': return 'clock';
      case 'performance': return 'chart-line';
      case 'financial': return 'bank';
      default: return 'file';
    }
  };

  const filteredReports = reports.filter(report => {
    if (filter.type !== 'all' && report.type !== filter.type) return false;
    if (filter.status !== 'all' && report.status !== filter.status) return false;
    return true;
  });

  const ReportCard = ({ report }: { report: ReportData }) => (
    <Card style={[styles.reportCard, { backgroundColor: theme.colors.surface }]}>
      <Card.Content>
        <View style={styles.reportHeader}>
          <View style={styles.reportTitleContainer}>
            <MaterialCommunityIcons 
              name={getTypeIcon(report.type)} 
              size={24} 
              color={theme.colors.primary} 
            />
            <Title style={[styles.reportTitle, { color: theme.colors.onSurface }]}>
              {report.title}
            </Title>
          </View>
          <Chip 
            style={[styles.statusChip, { backgroundColor: getStatusColor(report.status) }]}
            textStyle={{ color: 'white' }}
          >
            {report.status}
          </Chip>
        </View>
        
        <View style={styles.reportDetails}>
          <Paragraph style={[styles.reportPeriod, { color: theme.colors.onSurface }]}>
            Period: {report.period}
          </Paragraph>
          <Paragraph style={[styles.reportGeneratedBy, { color: theme.colors.onSurface }]}>
            Generated by: {report.generatedBy}
          </Paragraph>
          <Paragraph style={[styles.reportDate, { color: theme.colors.onSurface }]}>
            Created: {new Date(report.createdAt).toLocaleDateString()}
          </Paragraph>
          <Paragraph style={[styles.reportDownloads, { color: theme.colors.onSurface }]}>
            Downloads: {report.downloadCount}
          </Paragraph>
        </View>

        <View style={styles.reportActions}>
          <Button mode="outlined" compact style={styles.actionButton}>
            View
          </Button>
          <Button mode="outlined" compact style={styles.actionButton}>
            Download
          </Button>
          <Button mode="outlined" compact style={styles.actionButton}>
            Share
          </Button>
        </View>
      </Card.Content>
    </Card>
  );

  return (
    <ScrollView style={[styles.container, { backgroundColor: theme.colors.background }]}>
      <View style={styles.header}>
        <Title style={[styles.title, { color: theme.colors.onSurface }]}>
          Advanced Reporting
        </Title>
        <Paragraph style={[styles.subtitle, { color: theme.colors.onSurface }]}>
          Generate and manage comprehensive reports
        </Paragraph>
      </View>

      {/* Filter Section */}
      <Card style={[styles.filterCard, { backgroundColor: theme.colors.surface }]}>
        <Card.Content>
          <Title style={[styles.filterTitle, { color: theme.colors.onSurface }]}>
            Filters
          </Title>
          <View style={styles.filterRow}>
            <Chip
              selected={filter.type === 'all'}
              onPress={() => setFilter({ ...filter, type: 'all' })}
              style={styles.filterChip}
            >
              All Types
            </Chip>
            <Chip
              selected={filter.type === 'payroll'}
              onPress={() => setFilter({ ...filter, type: 'payroll' })}
              style={styles.filterChip}
            >
              Payroll
            </Chip>
            <Chip
              selected={filter.type === 'attendance'}
              onPress={() => setFilter({ ...filter, type: 'attendance' })}
              style={styles.filterChip}
            >
              Attendance
            </Chip>
            <Chip
              selected={filter.type === 'performance'}
              onPress={() => setFilter({ ...filter, type: 'performance' })}
              style={styles.filterChip}
            >
              Performance
            </Chip>
            <Chip
              selected={filter.type === 'financial'}
              onPress={() => setFilter({ ...filter, type: 'financial' })}
              style={styles.filterChip}
            >
              Financial
            </Chip>
          </View>
        </Card.Content>
      </Card>

      {/* Quick Stats */}
      <View style={styles.statsContainer}>
        <Card style={[styles.statCard, { backgroundColor: theme.colors.surface }]}>
          <Card.Content style={styles.statContent}>
            <MaterialCommunityIcons name="file-document" size={24} color={theme.colors.primary} />
            <Title style={[styles.statValue, { color: theme.colors.onSurface }]}>
              {reports.length}
            </Title>
            <Paragraph style={[styles.statLabel, { color: theme.colors.onSurface }]}>
              Total Reports
            </Paragraph>
          </Card.Content>
        </Card>
        
        <Card style={[styles.statCard, { backgroundColor: theme.colors.surface }]}>
          <Card.Content style={styles.statContent}>
            <MaterialCommunityIcons name="download" size={24} color="#4CAF50" />
            <Title style={[styles.statValue, { color: theme.colors.onSurface }]}>
              {reports.reduce((sum, r) => sum + r.downloadCount, 0)}
            </Title>
            <Paragraph style={[styles.statLabel, { color: theme.colors.onSurface }]}>
              Total Downloads
            </Paragraph>
          </Card.Content>
        </Card>
        
        <Card style={[styles.statCard, { backgroundColor: theme.colors.surface }]}>
          <Card.Content style={styles.statContent}>
            <MaterialCommunityIcons name="check-circle" size={24} color="#4CAF50" />
            <Title style={[styles.statValue, { color: theme.colors.onSurface }]}>
              {reports.filter(r => r.status === 'completed').length}
            </Title>
            <Paragraph style={[styles.statLabel, { color: theme.colors.onSurface }]}>
              Completed
            </Paragraph>
          </Card.Content>
        </Card>
      </View>

      {/* Reports List */}
      <View style={styles.reportsList}>
        {filteredReports.map((report) => (
          <ReportCard key={report.id} report={report} />
        ))}
      </View>

      {/* Generate New Report */}
      <Card style={[styles.generateCard, { backgroundColor: theme.colors.surface }]}>
        <Card.Content>
          <Title style={[styles.generateTitle, { color: theme.colors.onSurface }]}>
            Generate New Report
          </Title>
          <Paragraph style={[styles.generateDescription, { color: theme.colors.onSurface }]}>
            Create custom reports with advanced analytics and insights
          </Paragraph>
          <View style={styles.generateActions}>
            <Button 
              mode="contained" 
              style={styles.generateButton}
              onPress={() => console.log('Generate payroll report')}
            >
              Payroll Report
            </Button>
            <Button 
              mode="outlined" 
              style={styles.generateButton}
              onPress={() => console.log('Generate attendance report')}
            >
              Attendance Report
            </Button>
            <Button 
              mode="outlined" 
              style={styles.generateButton}
              onPress={() => console.log('Generate performance report')}
            >
              Performance Report
            </Button>
          </View>
        </Card.Content>
      </Card>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    padding: 16,
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 16,
    opacity: 0.7,
  },
  filterCard: {
    margin: 16,
    marginBottom: 8,
    elevation: 2,
  },
  filterTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  filterChip: {
    marginRight: 8,
    marginBottom: 8,
  },
  statsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    marginHorizontal: 4,
    elevation: 2,
  },
  statContent: {
    alignItems: 'center',
    padding: 16,
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 8,
  },
  statLabel: {
    fontSize: 12,
    textAlign: 'center',
    marginTop: 4,
  },
  reportsList: {
    paddingHorizontal: 16,
  },
  reportCard: {
    marginBottom: 12,
    elevation: 2,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  reportTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  statusChip: {
    marginLeft: 8,
  },
  reportDetails: {
    marginBottom: 12,
  },
  reportPeriod: {
    fontSize: 14,
    marginBottom: 4,
  },
  reportGeneratedBy: {
    fontSize: 14,
    marginBottom: 4,
  },
  reportDate: {
    fontSize: 12,
    opacity: 0.7,
    marginBottom: 4,
  },
  reportDownloads: {
    fontSize: 12,
    opacity: 0.7,
  },
  reportActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  actionButton: {
    marginLeft: 8,
  },
  generateCard: {
    margin: 16,
    elevation: 2,
  },
  generateTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  generateDescription: {
    fontSize: 14,
    marginBottom: 16,
  },
  generateActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  generateButton: {
    marginRight: 8,
    marginBottom: 8,
  },
});

export default AdminReporting;
